### ISSUE TITLE
Weird gray outline in PNG images with transparency

### ISSUE THREAD

**Issue by lfom** [robaho/seashore#76] opened 2019-07-29 13:21 UTC
First, thank you for this nice app, I have been using for a long time, long before it was in the App Store. I don't use it very often, but recently I noticed that there is a weird gray outline in PNGs with transparency that actually does not exist in the original image, but it shown in SeaShore, and it also remains if the image is saved. Please see the attached image of the same PNG opened in Preview and Seashore. I tried removing all files with "seashore" from my Library folder (aka reset settings) but I didn't help. I am running latest SeaShore 2.4.8 on High Sierra 10.13.6 on an iMac 21" 2011.

Regards

![Screen Shot 2019-07-29 at 10 04 04](https://user-images.githubusercontent.com/15659999/62051818-8f878e00-b1ea-11e9-9b62-aa623a524826.png)

**Comment by robaho** [comment] 2019-07-29 22:52
Can you please attach the original png image file? Thanks.

**Comment by robaho** [comment] 2019-07-29 23:52
@lfom The image file is very important, because In reviewing the photos, I think it may just be the transparency on top of the 'selected color'. With the original png file I will be able to determine for certain.

**Comment by lfom** [comment] 2019-07-30 00:44
Sure, no problem! Feel free to ask any more info. Thanks.

![sunrise](https://user-images.githubusercontent.com/15659999/62092030-0d2eb680-b24a-11e9-9a70-c2f74a32fb54.png)

**Comment by robaho** [comment] 2019-07-30 00:58
I have been able to reproduce. Thank you for reporting this - it is a serious problem.

**Comment by robaho** [comment] 2019-07-30 04:44
Thanks for reporting this. Fixed in 2.4.9. For maintainers, layers are not pre-multiplied, whiteboard is pre-multiplied.

**Comment by Chazwick4** [comment] 2024-01-03 06:28
Hello, I am having this problem as well. Had to do some digging to find someone else who has. I have version 3.33 running on a Mac M2 Max OS 14.2.1

I don't know what pre-multiplied means.

**Comment by robaho** [comment] 2024-01-03 12:46
Hi @Chazwick4 can you post a screenshot or video that demonstrates the issue please?

**Comment by Chazwick4** [comment] 2024-01-04 07:12
Hello, I actually tried some transparent PNG's again and it's totally fine. Sorry to alarm you. The issue only happens when opening old .xcf files (since this is a new computer with backed-up files from my old computer, which was running a much older version of Seashore). But I realize now I can delete the old PNG layers and replace them with new ones.

**Comment by robaho** [comment] 2024-01-04 13:53
Thanks for reporting back. If you have an old image with the problem you can attach it here or email it to me and I will ensure it is not a problem opening old images.

**Comment by Chazwick4** [comment] 2024-01-06 22:54
I'm going to make a new post, since it may be a different problem altogether, so you can keep this one closed.

**Closed** 2024-01-06 23:50 UTC
