### ISSUE TITLE
App crashes when trying to close the window

### ISSUE THREAD

**Issue by 0xfadeef** [robaho/seashore#30] opened 2019-01-12 14:03 UTC
Trying to close the app window with a window button or pressing Cmd+W results in "Seashore quit unexpectedly." dialog.

OS X 10.9.5, app version: 2.1.8

**Comment by 0xfadeef** [comment] 2019-01-12 17:14
@robaho There are no additional steps. You just start the app, open new file or some existing file, then try to close a window. That's it. Please check an excerpt from `system.log`:
```
Jan 12 20:07:02 AIR.local Seashore[30486]: find_shared_window: WID 12146
Jan 12 20:07:02 AIR.local Seashore[30486]: CGSOrderWindowListWithGroups: invalid window ID (12146)
Jan 12 20:07:02 AIR.local Seashore[30486]: CGSOrderWindowList: NULL list pointer or empty list
Jan 12 20:07:05 AIR com.apple.launchd.peruser.501[288] (app.seashore.56528[30486]): Job appears to have crashed: Segmentation fault: 11
Jan 12 20:07:05 AIR.local ReportCrash[30491]: Saved crash report for Seashore[30486] version 2.1.8 (201901092) to /Users/sergeyfadeev/Library/Logs/DiagnosticReports/Seashore_2019-01-12-200705_AIR.crash
```

**Comment by robaho** [comment] 2019-01-12 23:15
@0xfadeef is this working now that the effects are working ? I am thinking they may be related.

**Comment by robaho** [comment] 2019-01-12 23:16
@0xfadeef also, there should be a crash report in /Users/sergeyfadeev/Library/Logs/DiagnosticReports/ if you could attach that here if not resolved, I would appreciate it.

**Comment by robaho** [comment] 2019-01-13 23:14
Going to close this since I think it was related to the startup issues not being able to find core image.

**Comment by robaho** [comment] 2019-01-15 21:49
@0xfadeef I still can't reproduce. I need more details. If you open the application fresh, create a blank document, then use cmd-W does it crash? If you make some changes then use cmd-W do you get the prompt to save, and then does it crash?

The crash log shows it dying in OSX internals, and I can't reproduce, so it does possible point to a bug in Mavericks that Seashore is exposing.

Maybe if you take a video of exactly what you are doing and post it will be easier? I also need to now all of the "view" settings from that menu.

**Comment by robaho** [comment] 2019-01-15 22:05
@0xfadeef it may of been caused by the incorrect version compiling - the 2.2.0 release may fix the issue

**Comment by robaho** [comment] 2019-01-16 14:41
@0xfadeef did the 2.2 release resolve this for you?

**Comment by 0xfadeef** [comment] 2019-01-16 19:21
@robaho 
> did the 2.2 release resolve this for you?

Unfortunately, no. Still crashes.

> If you open the application fresh, create a blank document, then use cmd-W does it crash?

Yes. Same if you open some existing image after the app starts.

> If you make some changes then use cmd-W do you get the prompt to save, and then does it crash?

Depends. If you press "Don's save", then it crashes. If you choose to save the image, then **no, it doesn't crash**. Weird thing is, however, after you save the image, the app doesn't close the window. If you try to close again, **no crash**, all good.

> I also need to now all of the "view" settings from that menu.

I'm afraid I don't understand what "menu" are you referring to?

**Comment by 0xfadeef** [comment] 2019-01-16 19:25
Also, I'd like to mention that afair previous version of Seashore I had installed (don't remember version name) didn't have this bug on this OS.

**Comment by robaho** [comment] 2019-01-16 19:43
@0xfadeef are you using the version from the App Store? If so, you can use the "report to Apple" and I'll get a detailed report of the problem which might hopefully allow me to fix. Still can't reproduce in any way.

**Comment by robaho** [comment] 2019-01-17 04:19
@0xfadeef it appears it is a bug in the version of the OS you are running. There are similar reports to yours all over the web regarding the NSRulerView and this crash. That being said, there is a work-around I am going to try.

**Comment by robaho** [comment] 2019-01-17 06:12
Hopefully it is now fixed in 2.2.1 - not sure when that will get posted to the app store.

**Comment by 0xfadeef** [comment] 2019-01-17 19:18
@robaho Maybe you can provide dmg image for `2.2.1` so I can check whether the issue is actually resolved?

**Comment by 0xfadeef** [comment] 2019-01-17 19:33
![2019-01-17_22-32-35](https://user-images.githubusercontent.com/30846958/51343600-d19b7e80-1aa7-11e9-9356-3b36a8e51ae4.png)

**Comment by robaho** [comment] 2019-01-17 19:48
@0xfadeef I just downloaded the posted file and it opens fine for me - I think you need to use "save as", then use the finder to unzip it, then mount the dmg. It is probably a chrome thing auto-opening the zip.

**Comment by robaho** [comment] 2019-01-17 19:49
@0xfadeef I just downloaded with Safari - you might want to try that.

**Comment by 0xfadeef** [comment] 2019-01-17 20:09
@robaho Just repeated entire process several times downloading with Safari and I always unzip manually. Same result: _"Seashore.app" is damaged and can't be opened._

**Comment by robaho** [comment] 2019-01-17 20:13
@0xfadeef this may help https://secure.clcbio.com/helpspot/index.php?pg=kb.page&id=323 it is something with your system I think. I downloaded again and it opens fine.

**Comment by robaho** [comment] 2019-01-17 20:14
@0xfadeef this may be easier to follow https://www.iotgadgets.com/2018/09/how-to-fix-application-is-damaged-and-cant-be-opened-error-in-macos-mojave-and-high-sierra/

**Comment by robaho** [comment] 2019-01-17 20:15
@0xfadeef you may also just be able to right-click and open to get additional security prompts

**Comment by robaho** [comment] 2019-01-19 19:38
@0xfadeef I would really like to resolve this for you in the next release. To do that, I could use a little more prompt feedback, otherwise I am going to have to put it on the back-burner.

Please advise if you were able to open and run the DMG I attached here previously. Thanks.

**Comment by 0xfadeef** [comment] 2019-01-29 21:40
Still reproducible in `2.3.3` (see crash report below). **But** it looks like this time the issue only appears before the app is being used for a while. Could not reproduce on a fresh install.

[Seashore_2019-01-30-002835_AIR.log](https://github.com/robaho/seashore/files/2809772/Seashore_2019-01-30-002835_AIR.log)

**Comment by robaho** [comment] 2019-01-30 18:03
I am going to attempt one last fix to this in the next release. I honestly believe it is a bug in your installed OS version, because it is not being reported anywhere else - but I'll give it a try.

**Comment by robaho** [comment] 2019-01-31 22:23
@0xfadeef Can you find another app that uses rulers? Possibly Pages with rulers turned on, and see if it fails when trying to close the window ?

**Comment by robaho** [comment] 2019-02-01 05:33
@0xfadeef  Hi. I posted a 2.3.4.beta.dmg in the 2.3.3 releases. Can you please pull it down and see if it fixes this issue? Thanks for your help.

**Comment by 0xfadeef** [comment] 2019-02-01 21:43
@robaho I need some time to check if it's fixed, as I wrote the issue is not reproducible on a fresh install. I'll try to report asap.

**Comment by 0xfadeef** [comment] 2019-02-03 10:17
@robaho Not reproducible on version `2.3.4`.

**Comment by robaho** [comment] 2019-02-03 16:43
Great. Thanks for helping.

**Closed by robaho** 2019-02-03 16:43 UTC
