### ISSUE TITLE
Zoom tool: randomly moves into full zoom

### ISSUE THREAD

**Issue by bruceajames** [robaho/seashore#156] opened 2022-07-01 15:47 UTC
Seashore 3.0 on Mac OS Mojave 10.14.6

When the zoom tool is selected, either a zoom in or zoom out click will randomly change the zoom level to full zoom (3200% in the current image I'm editing)

**Comment by robaho** [comment] 2022-07-01 16:45
Can you please add a video/screencast of this? I cannot reproduce - but I don't have that version of OSX available.

**Comment by robaho** [comment] 2022-07-01 16:47
Are you by chance using a tablet/pen input? Does it happen when using the mouse? I think that former may be the reason. I will look into it.

**Comment by robaho** [comment] 2022-07-01 17:07
Actually, I think it may be the same problem that was causing the paste position errors.

**Comment by bruceajames** [comment] 2022-07-01 17:14
I am using a wireless 2 button wheel mouse. Playing around with it a little more, I think it might be taking a quick click as a click and drag, probably zooming into a very small 1x1 or 2x2 pixel area. I'm not able to reproduce it on the MacBook touchpad.

**Comment by robaho** [comment] 2022-07-01 17:37
Yes, I should probably require a minimum size to perform the zoom to rect.

**Comment by robaho** [comment] 2022-07-01 17:52
fixed in 3.02

**Closed by robaho** 2022-07-01 17:52 UTC
