### ISSUE TITLE
smudge tool

### ISSUE THREAD

**Issue by AxGiles** [robaho/seashore#183] opened 2023-01-09 05:14 UTC
The last half dozen times or so that I've used the Seashore app, the smudge tool has been all over the place.  Literally.  I will smudge in one direction - say from a certain point down and to the left - and the image will skid somehow.  It just jumps all over the place, messing up the image.  I do ctlr-z and undo, and the app switches from the smudge tool to the color selection tool, automatically, as if it was part of the undo action. 

Now, the smudge tool doesn't work at all.  I run it over a spot that I want to smudge, and nothing happens.  Except maybe a ghost of that spot appears somewhere else on the image as part of the skid.   Or part of the image will smudge, but not all of it, and not entirely. 

<img width="527" alt="image" src="https://user-images.githubusercontent.com/88804581/211244510-43d1c48c-a56c-4204-b29d-caae407d0ba6.png">

I rely on the smudge tool primarily. so this is pretty frustrating.  It's not working in three different ways now.  Could you guys please fix it?   Thanks.

**Comment by robaho** [comment] 2023-01-09 05:24
The undo switching to zoom I’ve seen - it’s typically caused by releasing the command before the Z - but I’m trying to work on a solution. 

As to the smudge tool - last I checked it was working fine. Are you certain you don’t have the rate too low? I will test tomorrow and post a video. 

Sorry for your troubles.

**Comment by AxGiles** [comment] 2023-01-09 16:55
I've tried it with different brush sizes, with the rate set at 100, and
fade-out on several different settings.  I'm sorry I don't know how to take
a video.  I'm sending a bunch of images.  I created a random white line on
a background (starting_point.png) and tried smudging it.  Nothing happened
at all at first (no_smudge.png) but then I got a little skid
(smudge_skid1.png), which I undid.  Then I got another, more dramatic skid
(smudge-skid2.png).   But half the time, it's not smudging at all.  The
image doesn't change at all.  And half the rest of the time, I get that
skid.  Is it something wrong with my computer?

thank you for your help.

**Comment by robaho** [comment] 2023-01-09 17:39
Do you use a pen/tablet or are you using a mouse?

**Comment by robaho** [comment] 2023-01-09 18:56
Also, have you tried with a single layer image where the layer size and position is equal to the image size (eg just create a new image and draw on it then smudge)

**Comment by AxGiles** [comment] 2023-01-09 19:01
I have had this problem using both the trackpad on my computer, and using
the wireless trackball (a logictack M70, I think it is).  Also, the images
I sent early this morning were exactly that - a single layer image with
size and position equal to the image size.  I drew on it and then smudged.

**Comment by AxGiles** [comment] 2023-01-09 19:02
Logitech M570 is what I meant to type there...

**Comment by robaho** [comment] 2023-01-09 19:06
Thanks. I will investigate tonight.

**Comment by AxGiles** [comment] 2023-01-09 19:28
Thanks!Sent from my iPhoneOn Jan 9, 2023, at 11:06 AM, robert engels ***@***.***> wrote:﻿
Thanks. I will investigate tonight.

**Comment by robaho** [comment] 2023-01-09 23:21
OK. I've reproduced several problems with the tool. It was working last I tested so I believe it is probably an easy fix.

**Comment by robaho** [comment] 2023-01-10 00:07
fixed in version 3.19 which will be posted to the app store tonight. Thank you for reporting this issue - it actually affected all of the paint tools when using smaller brushes with small brush spacing (smudge uses a spacing of 1% always).

**Closed by robaho** 2023-01-10 00:07 UTC

**Comment by robaho** [comment] 2023-01-10 00:25
Also, note that in the later releases you don't have to "smudge" to effect the blur. You can simply click (down/up), and it will blend & blur the area under the brush. Often by rapidly clicking in an area you can effect a better blend then trying to "smudge" the paint.

**Comment by AxGiles** [comment] 2023-01-10 00:36
Thanks and good to know, for all of the above! :D I appreciate it!  Sent from my iPhoneOn Jan 9, 2023, at 4:25 PM, robert engels ***@***.***> wrote:﻿
Also, note that in the later releases you don't have to "smudge" to effect the blur. You can simply click (down/up), and it will blend & blur the area under the brush. Often by rapidly clicking in an area you can effect a better blend then trying to "smudge" the paint.
