### ISSUE TITLE
REQ: option to default to [clipboard] for New images

### ISSUE THREAD

**Issue by luckman212** [robaho/seashore#114] opened 2020-02-01 15:08 UTC
I ❤️ Seashore! (Thank you)

My most common method for getting images into Seashore is via the clipboard. So, it would be handy to have a preference to allow selecting the default preset:
![image](https://user-images.githubusercontent.com/1992842/73593813-0b360080-44d6-11ea-8d6b-58bcdc6b4c9d.png)
e.g.
![image](https://user-images.githubusercontent.com/1992842/73594237-974a2700-44da-11ea-8c08-2cebb83d20ed.png)

(yes I know about ⌘⌥N but ... muscle memory)

**Comment by robaho** [comment] 2020-02-01 17:59
The problem is with your suggestion - that it only creates a blank image - that you then need to paste into - where as the 'File -> New from Pasteboard' does it all in one step.

**Comment by robaho** [comment] 2020-02-01 18:01
To be honest, I don't think that preset is working correctly anyway - as the behavior is different from the 'New from Pasteboard'. I need to look into it.

**Comment by robaho** [comment] 2020-02-01 18:02
It looks like the 'paste image' doesn't function like 'new from pasteboard' - it pulls a random image in Catalina.

**Comment by robaho** [comment] 2022-07-02 20:10
This is fixed in 3.02. "New from Pasteboard" is the easiest way.

**Closed by robaho** 2022-07-02 20:10 UTC
