### ISSUE TITLE
Erase tool and Fill tool issue

### ISSUE THREAD

**Issue by MinDeYuraDance** [robaho/seashore#218] opened 2024-11-16 05:15 UTC
Hello.

When I use the Fill tool on an area where I erased a line by pressing the Option key during the Pencil tool,
the line that should have been erased appears.

I attach a video:
https://github.com/user-attachments/assets/ff159ffa-d82f-4190-ba0c-117b49187e80

In the video, a rectangle, a circle, and a triangle are drawn,
the circle is left and the others are deleted, and then the Fill tool is used.
In this case, I expected the fill to be applied only to the circle,
but the fill is also applied to the erased lines.

If possible, I would like the erased area to not be filled.

I would appreciate your review and consideration.

*Environment
MacBook Pro 2023 (Apple M2 Max)
Sonoma 14.6.1
Seashore Ver. 3.39

*Translation tools are used.

**Comment by robaho** [comment] 2024-11-22 21:23
Thank you for reporting this. I was able to reproduce with some effort. You have a transparent background in the image, but you must have set the transparent color to white, so it was confusing.

I am working on a fix.

**Comment by robaho** [comment] 2024-11-22 22:20
The reason this occurs is because when you use the erase tool in Seashore it keeps the color channels, and removes the alpha channel. The fill tool was incorrectly comparing on only the color channels even when in 'all channels' mode. (This is the correct behavior if in 'color channels' mode).

I should have a fix posted tonight.

**Comment by robaho** [comment] 2024-11-22 22:51
This is fixed in 3.40

**Closed by robaho** 2024-11-22 22:51 UTC
