### ISSUE TITLE
Seashore won't save as png unless I change the file type first?

### ISSUE THREAD

**Issue by nightingale6374** [robaho/seashore#129] opened 2020-05-21 01:39 UTC
When I'm making a png file on seashore, when I go to save as, when I first change it from seashore file to png it saves just fine, but then when I edit it and try to save it as a png, unless I first change the file type to something else and then back to png, it saves as an XCF file.
Here's an example, the first file is the one that saves as a png, but the second one saves as something that I then can't even open.
![Screen Shot 2020-05-20 at 7 38 57 PM](https://user-images.githubusercontent.com/65692713/82513917-8f39e580-9ad1-11ea-96da-ebb3be62b02c.png)

**Comment by robaho** [comment] 2020-05-21 03:47
Thank you for reporting, but I cannot reproduce this after trying multiple times & ways. These are the exact steps I took - please tell me what you do differently:

1. open seashore.
2. file -> new -> create
3. make some edits
4. use 'file -> save as' choose PNG, and save
5. make some more edits
6. use 'file -> save'
7. close seashore

At this point I have an 'Untitled' PNG file on my desktop that opens fine.

I also tried quitting Seashore after step 4, then re-opening and it worked fine.

Are you using version 2.5.9 (the latest)? There were some bugs involving saving a while back.

Please report back and I'll try and get it resolved. Maybe if you could attach a video of you doing the steps it might be easier. Thanks for your help.

**Comment by robaho** [comment] 2020-05-21 03:49
Also, one other thing - did you try changing the name when using Save As? Does that work? There is special handling of 'Untitled' files. I doubt this will help (as I tried both ways and couldn't reproduce the problem).

**Comment by robaho** [comment] 2020-05-21 03:54
One more thing, when you create the new image, can you attach a screen shot of the image options you are using. Thanks.

**Comment by nightingale6374** [comment] 2020-05-21 04:11
Molly Norman has shared a OneDrive file with you. To view it, click the link below.
<https://1drv.ms/u/s!AlYbtNYfOWt7hRaXInCy8JAWqx85>
[https://r1.res.office365.com/owa/prem/images/dc-mpg_20.png]<https://1drv.ms/u/s!AlYbtNYfOWt7hRaXInCy8JAWqx85>
2020-05-20 22-05-46.mp4<https://1drv.ms/u/s!AlYbtNYfOWt7hRaXInCy8JAWqx85>

Hello, Mr. Robert,

Since you were not able to replicate my issue and I have difficulty describing, I screenrecorded everything. I explain as I go along in a text file more specifically what my problems are and how they're playing out, but hopefully this answers all of your questions. At the end I check and see that I do have an update pending, but I have updated and still am experiencing the problems I described. I hope this helps.

Molly
________________________________

**Comment by robaho** [comment] 2020-05-22 04:44
Hi Molly,

Thank you for the video - I was now able to replicate the issue! I'll have it fixed in the next release.

**Comment by robaho** [comment] 2020-05-22 05:14
fixed in 2.5.10

The issue was that is was saving with the wrong extension - if you would have renamed the XCF file to PNG it would have opened ok.

The problem was caused because the file extension needed to be initialized based on the item already selected in the combo box - otherwise it was defaulting to xcf.

**Closed by robaho** 2020-05-22 05:14 UTC
