### ISSUE TITLE
Seashore won't close 

### ISSUE THREAD

**Issue by MurrayElliot** [robaho/seashore#137] opened 2020-07-22 18:42 UTC
MACOs High Sierra
MacBook Pro (15-inch, Mid 2012)

Got Seashore into a state where 'Quit' is greyed out in Seashore menu.
RIght-click on Icon followed by Quit does nothing. If I 'Show all WIndows' there's no other windows.
I eventually found Seashore in the activity monitor (just the Icon, no name) to force quit it from there.

Can't be sure what I did to create this situation. It was my first time using Seashore so I was doing lots of tests!

**Comment by robaho** [comment] 2020-07-24 03:38
Thank you for providing this. There has been similar reports in the past, but I've never been able to track it down. I "think" it may be related to closing a file when it has changes, and getting the auto-save but somehow the file couldn't be saved - putting the app into a strange state.

There's not a lot I can do without some "steps to reproduce", so I am asking for your help - if you think you can narrow down what you did please let me know.

It could also be related to opening certain files causing some internal corruption.

Again, any help you could provide would be appreciated.

**Comment by robaho** [comment] 2021-02-11 04:52
closing as duplicate of #83

**Closed by robaho** 2021-02-11 04:52 UTC
