### ISSUE TITLE
Font handling is broken

### ISSUE THREAD

**Issue by tnakagome** [robaho/seashore#14] opened 2018-12-25 00:26 UTC
When I try to insert a text, it is shown like black and white stripes.
This occurs on both the latest MacOS 10.14 (just upgarded) and 10.13.6.

<img width="836" alt="2018-12-25 9 18 19" src="https://user-images.githubusercontent.com/19327519/50408022-d5304280-0826-11e9-96d9-00977187b33f.png">

Thanks.

**Comment by robaho** [comment] 2018-12-26 16:37
@tnakagome can you reproduce this with version 1.0.0 ? I need exact steps to reproduce, because it works for me.

**Comment by robaho** [comment] 2018-12-28 02:00
Also, I only have 10.13.6, and version 1.1.2 is working for me.

**Comment by tnakagome** [comment] 2018-12-31 10:30
It's as simple as creating a new image and insert a text. I was using 0.6.6 when I reported, but it still happens on 1.1.3 with 10.14. My OS language is Japanese, if that matters.

**Comment by robaho** [comment] 2018-12-31 15:55
I will try reviewing the relevant code again, but it is very hard to fix if I can’t make it happen. Also I can’t run 10.14 only 10.13 so I’m stuck a bit.

**Comment by robaho** [comment] 2018-12-31 23:57
@tnakagome did you try with the 'high quality fringe' disabled ? Also, are you sure you don't have a 'texture' selected, maybe from a saved setting ?

**Comment by robaho** [comment] 2019-01-01 00:01
@tnakagome also, can you please try with a standard font, like Lucidia, and ascii characters and report if it works. Thanks.

**Comment by tnakagome** [comment] 2019-01-01 02:08
I have set the OS primary language to English and recorded a video, with "high quality fringe" turned off.

This is on Macbook Pro (13-inch 2016 model)
- 3.3GHz Intel Core i7
- 16GB RAM
- Intel Iris Graphics 550 1536MB
with MacOS 10.14.

Interestingly, this did not happen a year ago on the same machine running 10.13. Maybe a few OS patches got applied since then. Not sure what else have changed.

[Screen Recording 2019-01-01 at 10.58.19.mov.zip](https://github.com/robaho/seashore/files/2719067/Screen.Recording.2019-01-01.at.10.58.19.mov.zip)

**Comment by robaho** [comment] 2019-01-01 16:12
@tnakagome thanks for the video, but it is not "wide enough" for me to see the color settings in the upper right corner. a screen capture of those would be fine.

A shout out to anyone running this on 10.14... Is it working for anyone ?

**Comment by robaho** [comment] 2019-01-01 21:33
should be fixed in 2.0, I believe it is caused by graphics setups that use planar data, or possibly retina displays - either which I can't test, but it seems the text code was using a similar pattern as other code that was broken in this regard.

one thing to note, sub-pixel antialiasing is disabled, since it is really only useful when displaying on a monitor, and should not be in the pixel/image data itself. This should allow for more consistent font rendering.

also, the 'fringe' works, so you can pick up the underlying color information, but it is debatable if this should be used - since the text uses alpha pixels anyway - it will like any other when the layer is composited.

**Closed by robaho** 2019-01-01 21:33 UTC

**Comment by tnakagome** [comment] 2019-01-03 01:13
Working fine now. Thanks!
